[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.31.0",
    "boto3>=1.43.103",
    "fastapi[standard]>=0.138.1",
    "httpx>=0.28.1",
    "lancedb>=0.33.0",
    "loguru>=0.7.3",
    "networkx>=3.7",
    "pydantic>=2.13.4",
    "tomli>=2.4.1",
    "uvicorn>=0.49.0",
]

[dependency-groups]
test = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
]
